### ISSUE TITLE
AS a developer, I want the project to use a linter

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/random-bunny#67]
AS a developer, I want the project to use a linter
SO THAT I can keep a consistent code style across the entire project

## Acceptance Criteria
AS a developer
GIVEN I want to check code styles
WHEN I run `yarn lint`
THEN the project will be checked for its code style

AS a developer and tester
GIVEN I want to check code styles
WHEN a CI pipeline runs
THEN it will also run the `yarn lint` command

## Subtasks
- [ ] Install and configure `eslint`
- [ ] Setup `yarn lint` command
- [ ] Update CI pipelines
