### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/random-bunny#7]
I need to migrate the project to using TypeScript. This will allow me to take advantage of the benefits TypeScript gives over JavaScript, such as Type safety.

## Subtasks
- [x] Install and setup TypeScript
- [x] Migrate script
- [x] Update documentation to reflect changes

## Outcomes
- [x] The entire project will be fully written in TypeScript

## Blocks
- #12
