### ISSUE TITLE
AS a package user, I want to be able to output the image as a converted ASCII art

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/random-bunny#87]
Epic: \
Story Points:

---

AS a package user, I want to be able to output the image as a converted ASCII art
SO THAT I can for fun see the image in the terminal

## Acceptance Criteria

AS a package user
GIVEN I want to see the ASCII art
WHEN I use the flag `-a` or `--ascii`
THEN the output should be the image converted into ascii

AS a package user
GIVEN I want to see the ASCII art in colour
WHEN I use the flag `-ac` or `--ascii --colour`
THEN the output should be the image converted into ascii with 8 bit colour

AS a package user
GIVEN I want to change the size of the ASCII art
WHEN I use the flag `-a --size=100` or `--ascii --size=100`
THEN the output should be the image at the size of 100x100

## Subtasks

- [ ] Add the `--ascii` / `-a` flag
- [ ] Add the `--colour` / `-c` flag
- [ ] Add the `--size` flag
- [ ] Update tests
- [ ] Update documentation

## Notes

- https://www.npmjs.com/package/ascii
- The flags `--colour` and `--size` should only be allowed to be used when `--ascii` is supplied
